# fly.toml app configuration file generated for cs-eslam-hatem on 2025-11-02T10:52:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cs-eslam-hatem'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 8
  memory_mb = 16384

[[mounts]]
source = "storage"
destination = "/data"
